Session8
yumemi-inc/iOS-training-Ryosuke pull request #10
Opened 2023-06-30 02:55 UTC by Ryosuke1025

# やったこと
・Notification Centerを使って、イベント通知を実装
・CombineでNotification Centerの購読をするようにした

# 使ってみた

https://github.com/yumemi-inc/iOS-training-Ryosuke/assets/106091028/ac1ba690-92d8-46fa-acc6-f3979b929f39

# 備考
・特に無し

2023-06-30 09:29 UTC, novr requested changes
[MUST] エラーが表示中に、バックグラウンドから復帰すると天気が更新されてしまいます

[OPTION] また、エラー表示中に再度エラーが発生すると以下のログが出力されます
このログを抑制するにはどうしたらいいか考えてみましょう
```
2023-06-30 18:26:48.986304+0900 ios-training-Ryosuke[54336:19810083] [Presentation] Attempt to present <UIAlertController: 0x136015000> on <ios_training_Ryosuke.WeatherViewController: 0x131e05540> (from <ios_training_Ryosuke.WeatherViewController: 0x131e05540>) which is already presenting <UIAlertController: 0x13500b000>.
```

2023-07-03 07:57 UTC, novr commented on ios-training-Ryosuke/Controller/WeatherViewController.swift
> +    private var isShowingError = false
[imo] このプロパティは必要でしょうか？
自分で管理するプロパティはなるべく少なくするといいです

このようなプロパティもあるので利用を考えてみましょう
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621407-presentedviewcontroller

2023-07-07 01:31 UTC, Ryosuke1025 commented on ios-training-Ryosuke/Controller/WeatherViewController.swift
> +    private var isShowingError = false
https://github.com/yumemi-inc/iOS-training-Ryosuke/pull/10/commits/5bec610c8c23191da13e941cc8a9555b93b5dbbf

このコミットで対応しました！
自分で管理するプロパティより、UIViewControllerのプロパティを使った方が簡潔に書けますし、何より保守性も上がりそうですね。

2023-07-10 05:35 UTC, shinya-todaka approved these changes
LGTM

2023-07-10 05:36 UTC, merged